- name: bootstrap monitoring server
  hosts: influxdb
  become: True
  vars:
#    loki_server: loki_server.local
  roles:
#    - fahcsim.grafana_stack.prometheus
#    - fahcsim.grafana_stack.loki
    - fahcsim.grafana_stack.prometheus_node_exporter
    - fahcsim.grafana_stack.prometheus_alert_manager
#    - fahcsim.grafana_stack.promtail
#    - fahcsim.grafana_stack.grafana

- name: monitoring hosts
  hosts: debian
  become: True
  vars:
#    loki_server: loki_server.local
  roles:
    - fahcsim.grafana_stack.prometheus_node_exporter
    - fahcsim.grafana_stack.prometheus_alert_manager
#    - fahcsim.grafana_stack.promtail
