---
- name: Run Watchtower once on Docker hosts
  hosts: all
  remote_user: root

  tasks:
    - name: Ensure docker python library is installed (required by docker_container module)
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Run Watchtower container once to update containers
      community.docker.docker_container:
        name: watchtower_run_once
        image: containrrr/watchtower
        command: "--run-once"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        auto_remove: true
        state: started
        detach: false
      register: watchtower_result

    - name: Display Watchtower logs/output
      ansible.builtin.debug:
        msg: "{{ watchtower_result.container.Output }}"
      when: watchtower_result.container is defined and watchtower_result.container.Output is defined